run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: macconv
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  depguard:
    packages:
      - github.com/spf13/cobra
      - github.com/spf13/pflag
      - github.com/inconshreveable/mousetrap
      - macconv/pkg/errors
      - macconv/pkg/logger
      - macconv/pkg/validator
    rules:
      cmd/:
        allow:
          - github.com/spf13/cobra
          - macconv/pkg/errors
          - macconv/pkg/logger
      cmd/root.go:
        allow:
          - github.com/spf13/cobra
          - macconv/pkg/logger
      cmd/mac.go:
        allow:
          - github.com/spf13/cobra
          - macconv/pkg/errors
          - macconv/pkg/logger
      cmd/ip.go:
        allow:
          - github.com/spf13/cobra
          - macconv/pkg/errors
          - macconv/pkg/logger
      cmd/tcp.go:
        allow:
          - github.com/spf13/cobra
          - macconv/pkg/logger
      cmd/dhcp.go:
        allow:
          - github.com/spf13/cobra
          - macconv/pkg/errors
          - macconv/pkg/logger
      cmd/version.go:
        allow:
          - github.com/spf13/cobra
      pkg/validator/validator.go:
        allow:
          - macconv/pkg/errors

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - goconst
    - path: cmd/
      linters:
        - gochecknoinits
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true